--liquibase formatted sql
--changeset dkomrakov:1.0
CREATE SCHEMA IF NOT EXISTS DOMAIN_SCHEMA
--rollback DROP SCHEMA IF EXISTS DOMAIN_SCHEMA

--changeset dkomrakov:2.0
--precondition-sql-check expectedResult:0 SELECT Count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='CLIENTS' AND TABLE_SCHEMA='DOMAIN_SCHEMA'
create table DOMAIN_SCHEMA.CLIENTS(
    LOGIN varchar NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (LOGIN)
)
--rollback drop table DOMAIN_SCHEMA.CLIENTS

--changeset dkomrakov:3.0
--precondition-sql-check expectedResult:0 SELECT Count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='BALANCES' AND TABLE_SCHEMA='DOMAIN_SCHEMA'
CREATE TABLE DOMAIN_SCHEMA.BALANCES(
    LOGIN varchar NOT NULL UNIQUE,
    BALANCE long,
    FOREIGN KEY (LOGIN) REFERENCES DOMAIN_SCHEMA.CLIENTS(LOGIN)
)
--rollback drop table DOMAIN_SCHEMA.BALANCES

--changeset dkomrakov:4.0
CREATE INDEX IDX_BALANCE ON DOMAIN_SCHEMA.BALANCES (LOGIN)
--rollback ALTER TABLE DOMAIN_SCHEMA.BALANCES DROP INDEX IDX_BALANCE;

--changeset dkomrakov:5.0
--precondition-sql-check expectedResult:0 SELECT Count(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='CREDENTIALS' AND TABLE_SCHEMA='DOMAIN_SCHEMA'
CREATE TABLE DOMAIN_SCHEMA.CREDENTIALS(
    LOGIN varchar NOT NULL UNIQUE,
    PASSWORD_HASH varchar NOT NULL,
    SALT_HASH varchar NOT NULL,
    FOREIGN KEY (LOGIN) REFERENCES DOMAIN_SCHEMA.CLIENTS(LOGIN)
)
--rollback drop table DOMAIN_SCHEMA.CREDENTIALS

--changeset dkomrakov:6.0
CREATE UNIQUE INDEX IDX_CREDENTIALS ON DOMAIN_SCHEMA.CREDENTIALS (LOGIN)
--rollback ALTER TABLE DOMAIN_SCHEMA.CREDENTIALS DROP INDEX IDX_CREDENTIALS
